### ISSUE TITLE
Only keep the most recent version of resources from discovery interface

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1047]
As part of the resource versioning work, https://github.com/hydroshare/hydroshare/issues/946, we need to remove original resources from searches and add the newly created version into the search. This work depends on implementation of on-demand search index update as detailed in issue  https://github.com/hydroshare/hydroshare/issues/755. After on-demand search index update is implemented, I will work on this issue.

**Comment by alvacouch** [comment]
This is addressed in issue #1164 (pending approval).

**Comment by hyi** [comment]
@alvacouch @xuezhaokun Did the issue #1164 solr real time index update address this issue as well? I don't think it does since the obsoleted public or discoverable resources will remain being public or discoverable, which means it will still show up in the discovery interface even though this resource is obsolete and has been superseded by a newer version. The resource version chain is established via Relation metadata elements, so I think some special processing is needed in solr-haystack related code to remove these obsoleted public/discoverable resources from solr index when a newer version is created that obsoletes a public or discoverable resource. Can you confirm whether my comment is correct or not?

**Comment by hyi** [comment]
closing this issue since it is a duplicate of the issue #1998
