### ISSUE TITLE
Add folder operations to REST API

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1495]
This is needed by a use case for @horsburgh whose group need to automate publication of their quality controlled data from each of their iUTAH continuous monitoring sites to HydroShare. Their plan is:
1. They would like to have one Generic Resource per monitoring sites
2. Within each resource will be several folders, one for each quality controlled time series measured at that site
3. Inside each folder will be a CSV file of the quality controlled data and some additional files, including a Python script that was used to create the quality controlled data

**Comment by horsburgh** [comment]
@hyi - thanks for adding this. This is a specific use case of a more general problem/issue which is that we would like to create and modify folder structures within resources through the REST API and the Python REST client.

**Comment by alvacouch** [comment]
@hyi @dtarb @pkdash 
Work started in branch "1495-REST-API-for-folders".

To reduce the complexity of use, I plan a stateless REST API for folders. What I mean by this is that folders that are needed are created when named in a path. This means that there will be no separate REST folder create, but there will be a separate REST folder (or object) delete. This is a tradeoff between power and safety: 

1. Power: one REST request can do a lot, including creating a hierarchy of folders. 
2. Safety: one needs to be able to undo massive, incorrect actions. 

In this case, power wins over safety, because there is no compelling reason that one should have to create each folder in a path separately in the REST API: permissions are the same for all folders. Thus, a folder is logically a tag rather than a location (which is the way iRODS handles them). 

Some issues: 
1. What are the naming restrictions for folders? I think -- rather obviously -- that folders shouldn't be able to conflict with names for files. What else?

**Comment by dtarb** [comment]
I'd prefer not to be more restrictive on naming than a mainstream system such as linux.  So if it is a legitimate linux folder name, we should take it.  If not, I'd be OK to reject it.  I'd prefer to do this than have to think through all the rules ourselves.

**Comment by alvacouch** [comment]
@dtarb But we are allowing some rather clueless things now. 

For example, we are mapping the mime type from /etc/mime.types, as a function of the filename. If we allow a folder to conflict with a valid file name, e.g., by ending with a valid file extension, we will have a lot more states to deal with than if we simply avoid that. 

This is a question of power versus usability. 

1. more power means we can name folders anything and then have state botches when someone names a folder with the name of a resource and then tries to define the resource. 
2. more usability means that it simply isn't possible to get into that situation.

**Comment by alvacouch** [comment]
As another general comment, I plan to allow recursive hierarchy delete by default. If one creates 
cat/dog/foo/bar/baz.csv, and then does a DELETE cat, the whole hierarchy is removed. Again this is a matter of power versus usability. One might argue that it is "too powerful", but I would argue that anyone messing around with the REST API had better know what they're doing beforehand. I certainly **hope** that people using the API are aware of the issues. 

An option "safe=True" will refuse to delete non-empty folders.

**Comment by dtarb** [comment]
@alvacouch I am OK for you to do whatever you feel is best.  I was thinking of a use case where a model instance is on a Linux computer and has several (hundred) files nested in Linux folders and they all follow Linux rules.  The user zips up the whole thing, loads it into HydroShare and tries to unzip.  We don't want rules we have imposed to limit this.  The same could be said for Windows folder and file name rules, but Linux and Windows do not always agree, and where there is a choice, I'd go with Linux.  

I am OK with your recursive delete approach.

**Comment by hyi** [comment]
@alvacouch @dtarb It looks like linux does not allow to create a directory with the same name as a file in that directory. ```cannot create directory: file exists``` error will be raised if trying to do so. I also tried to make a logical collection in iRODS with the same name as a data object file in that collection/directory, and I got an iRODS exception ```CAT_NAME_EXISTS_AS_DATAOBJ``` So in any case this cannot be done and an exception will be raised. It would be simpler to leave this to the iRODS/linux to handle, but if you want to add a check in REST API to disallow this before getting to the linux and iRODS layer, it'd be great. The functions I added for folders that can be used by REST API already supports recursive folder creation and deletion, so that would be fine. Let me know if you find any folder-related functions need to be augmented for REST API use, though.

**Comment by alvacouch** [comment]
@dtarb @hyi @pkdash 
In the interest of getting this going quickly with a minimal rewrite of the code, I have had to make some design simplifications. The existing code assumes that when doing a PUT of a file, the directory already exists. Making the code create that directory is difficult, because REST calls should exhibit **transactional atomicity,** i.e., they should either succeed or not, and never "half succeed". The code to recover from creating a hierarchy of directories, creating a file within the lowest directory, and then undoing that because of a file validation failure is too complex and will take too long to write. Thus, I have had to compromise and create a more "traditional" approach to folders in which folders already exist before one can PUT a file into them. This requires almost no modifications of existing code. 

The way this will work is that there will be a new endpoint "folders", which allows "create folder" and "remove folder". 

| endpoint | meaning | caveats | 
|------------|-----------|---------|
| PUT /resource/{id}/folders/{path}/ | make a folder exist if it doesn't exist | recursive; fails if a path component is already a file |
| DELETE /resource/{id}/folders/{path}/ | delete the named folder | recursively deletes subfolders; fails if there is any file in the hierarchy to be deleted |
| GET /resource/{id}/folders/{path}/ | lists files in the folder or subfolders | recursive; skips folder names |
| GET /resource/{id}/folders/ | lists all folders | recursive; lists subfolders |
 
The use of PUT -- rather than POST -- is rather subtle. POST is supposed to raise an error if the folder already exists. PUT is an update; if the folder already exists it just returns "success" (200); if it creates anything it returns "created" (201). Thus, **PUT can be used repeatedly to ensure that a folder exists before writing to it.**  A client can safely and repeatedly PUT a folder before PUTting a file into it, to wit: 

```
PUT /resource/{id}/folders/cat/dog/
PUT /resource/{id}/files/cat/dog/bear.csv/
```
and this will assure that the folder exists before writing to it. The first request can be repeated as many times as desired without harm. 

Likewise, to delete a folder, one must iterate over the output of 
```GET /resource/{id}/folders/{path}/```
and delete all of the listed files with 
```DELETE /resource/{id}/files/{filepath}/```
before doing a 
```DELETE /resource/{id}/folders/{path}/```
The REST client can do this easily. 

I could easily create a POST endpoint

| endpoint | meaning | caveats |
|-----------|-----------|----------|
| POST /resource/{id}/folders/{path}/ | create folder | raise error if folder exists | 

but this does not seem necessary.  PUT should be enough for all known use cases. 

So, 

1. REST transactional atomicity is easy to ensure in this design. 
2. The REST client can still create folders seamlessly before uploading a file by making two REST requests in sequence inside the same client call. 
3. At the user's option, the REST client can also recursively delete a hierarchy of files.

**Comment by alvacouch** [comment]
@hyi @pkdash 
I've started writing the above and have found the appropriate routines to write most of it. 

One gaps so far: I need to be able to determine whether a particular path is a file or folder. I think this is a matter of calling ils -l and then parsing the output. This will require modifications to django_irods/storage (for general irods objects) and hs_core/views/utils.py (for resources).

**Comment by alvacouch** [comment]
@pkdash: where are you storing file type metadata in Django now? There is new code in the iRODS interface that is intended to sweep out folder data from Django, but currently, it only deletes ResourceFile objects for files that iRODs deletes. Will that suffice or is other cleaning necessary?

**Comment by pkdash** [comment]
@alvacouch Though I have not unit tested what happens to the file level metadata when a folder is deleted, I am assuming as part of the folder delete, all files in that folder get deleted. That should cleanup the file level metadata data. The code that I have implemented for cleaning of file level metadata is that if any file (ResourceFile object) in a logical file group (an instance of AbstractLogicalFile)  is deleted then all files in the group get deleted and the logical file object finally gets deleted. The deletion of the logical file object results in deletion of all file level metadata. So no additional cleaning is necessary.

**Comment by pkdash** [comment]
@alvacouch 

>  Thus, I have had to compromise and create a more "traditional" approach to folders in which folders already exist before one can PUT a file into them. This requires almost no modifications of existing code. 

I agree to the above approach. More granular level rest endpoints are better as they are more reliable (less likely to fail).

**Comment by alvacouch** [comment]
@pkdash : I still don't understand. What happens now is that 

1. All files are deleted with the folder. 
2. For each file, the ResourceFile object is deleted. 

Is there anything else -- other than the ResourceFile object -- that needs to be deleted in Django?

**Comment by hyi** [comment]
@alvacouch This statement "The existing code assumes that when doing a PUT of a file, the directory already exists" is not true, the current code as shown here https://github.com/hydroshare/django_irods/blob/master/storage.py#L188-L192 actually creates directory as needed if you pass in ```create_directory``` a value of ```True```.

**Comment by pkdash** [comment]
@alvacouch 

> Is there anything else -- other than the ResourceFile object -- that needs to be deleted in Django when a file is deleted? 

As per the current code in develop branch, I don't think anything else needs to be deleted. However, as part of my work on file type metadata, file level metadata needs to be deleted when a folder gets deleted which I will have to implement.

**Comment by alvacouch** [comment]
@pkdash If that metadata is stored in the ResourceFile object for each file, then there will be nothing to do. The current code deletes hanging ones of these. Then it can still be serialized into resourcemetadata.xml document, even though it is stored elsewhere.....

**Comment by alvacouch** [comment]
@hyi This is what I have found of your code: 

1. `hs_core/hydroshare/utils.py `contains file-level operations on federated zones. 
2. `hs_core/views/resource_folder_hierarchy.py `contains primitive REST functions that operate on specific folders. These are mapped  in hs_core/urls.py to **internal** REST endpoints and used in the UI. 
3. `hs_core/views/utils.py `contains various folder utilities, including the base code to create a folder, delete a folder, and clean up Django after folder deletion. 

Am I missing anything?

**Comment by hyi** [comment]
@alvacouch Yes, you get them all correct. I think those folder utilities in  ```hs_core/views/utils.py``` should be able to be directly used by REST API end points for folder-related functionalities, in the similar way as they are used by internal view functions in ```hs_core/views/resource_folder_hierarchy.py```. Let me know if you have questions.

**Comment by pkdash** [comment]
@alvacouch  File metadata is not part of the ResourceFile object. There is now a LogicalFile object that holds file level metadata.

**Comment by alvacouch** [comment]
@pkdash Exactly why do we need the `LogicalFile` object to be separate from `ResourceFile`? Is it because a LogicalFile can refer to a reference instead of a physical file?

**Comment by alvacouch** [comment]
@hyi @pkdash There are now multiple points of truth for deleting a file: hs_core/hydroshare/resource.py and hs_core/views/utils.py The one in hs_core/hydroshare/resource.py is definitive, currently in use, and does more. The one in hs_core/views/utils.py does not emit a necessary pre-delete signal, and is redundant. 

@pkdash **Could you please update `hs_core/hydroshare/resource.py`: `delete_resource_file`** to delete logical file metadata as part of your PR? I will consider this version definitive and rewrite `delete_resource_folder` to depend upon it.

**Comment by pkdash** [comment]
@alvacouch 

> Exactly why do we need the LogicalFile object to be separate from ResourceFile? Is it because a LogicalFile can refer to a reference instead of a physical file?

Since a specific file type can have more than one physical file (ResourceFile), the LogicalFile allows us  to refer to more than one physical file. The file type metadata is part of the LogicalFile and not part of any specific physical file. By having a LogicalFile  all business logic specific to a file type is implemented as part of the LogicalFile.

**Comment by pkdash** [comment]
@alvacouch 

> Could you please update hs_core/hydroshare/resource.py: delete_resource_file to delete logical file metadata as part of your PR?

> Looks like you also need to revise hs_core.views.utils.remove_irods_folder_in_django because it assumes that a whole folder hierarchy has been deleted.

My PR on raster file type already addressed the above needed changes.

**Comment by alvacouch** [comment]
See issue #1629

**Comment by pkdash** [comment]
The composite resource type does not use ```pre_file_delete``` signal. As part of the ```remove_irods_folder_in_django``` function the LogicalFile objects are deleted prior to deleting the associated ResourceFile objects. The deleting of LogicalFile object deletes associated file type metadata.

**Comment by alvacouch** [comment]
That still leaves me with the problem of the other resource types that do use the signal to delete metadata in auxiliary tables.

**Comment by alvacouch** [comment]
See PR #1672 for the initial implementation, for GenericResource only, using the advice here.

**Comment by pkdash** [comment]
@alvacouch I assume this has been implemented.

**Comment by pkdash** [comment]
@hyi I think this should be closed.
