### ISSUE TITLE
Verify zipped bag exists before "Copy Resource Bag to iRODS User Zone"

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2724]
See @ChristinaB 's  error here https://github.com/hydroshare/hydroshare/issues/2662#issuecomment-384010685 with this resource https://www.hydroshare.org/resource/ec518c49772b420b97047f7482ae92aa/  when trying to "Copy Resource Bag to iRODS User Zone"

I checked and ec518c49772b420b97047f7482ae92aa.zip bag does not exist in the bags directory /hydroshareuserZone/home/localHydroProxy/bags 

Regardless, will likely need iRODS 4.2.3 installed first to fix the .zip bag creation bug associated with iRODS 4.2.2 here https://github.com/hydroshare/hydroshare/issues/2661

**Comment by hyi** [comment]
@rayi113 @ChristinaB The current code checks ```bag_modified``` flag to determine whether the bag needs to be regenerated. For this specific resource, if bag does not exist, ```bag_modified``` flag should be set to True, so it can be regenerated when trying to copy this resource to user zone. It looks like ```bag_modified``` flag got messed up for this specific resource. I can update the code to check whether the bag actually exists, similar to when the bag is downloaded, to make sure the bag is recreated if bag does not exist.

**Comment by aphelionz** [comment]
@hyi  Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by dtarb** [comment]
There are still 3 problems with the resource mentioned here
https://www.hydroshare.org/resource/ec518c49772b420b97047f7482ae92aa/
- Right click to download content file does not work
- Copy bag to iRODS user zone results in error
- Download bag does not work (or hangs forever)

**Comment by dtarb** [comment]
Update.  It is actually possible to download a bag on beta.hydroshare.org (immediately after 1.16 deploy while beta has 1.16 candidate release code in it).  This suggests the problem may be iRODS related as www has an older iRODS than beta.  @hyi can you please look into this and indicate whether there is anything beyond just waiting for iRODS update to be done to fix this.

**Comment by hyi** [comment]
@dtarb I looked into this issue. The problem on production is caused by this iRODS ibun error ```bunUtil: opr error for ..., status = -530039 status = -530039 UNIX_FILE_LINK_ERR, Directory not empty```. The resource is stored in the user zone due to its around 3GB size. I also found there was no zipped bag files under user zone, so it looks like the bags directory got wiped out or something on userzone. Then I tested it out to create a new resource from user zone and then downloaded the bag successfully, so the functionality works with the issue being isolated for this resource. However, I can manually run icommands using the same irods environment on production to zip this bag successfully via ibun. But when I manually run irule command to run bagit rule trying to create bag-related manifest files, it failed on me with SYS_INTERNAL_ERR. I did not know what is going on with this resource after spending a lot of time on it, and cannot conclude it is related to iRODS versions at this point.

**Comment by dtarb** [comment]
@hyi so what do you recommend at this point.  Is this something that you, @rayi113 @cbcunc could discuss and recommend a path forward.  It may be easiest to copy the resource, delete the derived from link and set the owners back to the current owners, then acting as admin delete the resource.

But I worry that this is a symptom of iRODS problems that we need to get to the bottom of.

**Comment by hyi** [comment]
@dtarb I have spent more time investigating this resource and here is what I found. Initially that resource only included readme.txt file and data directory that has the single zip file and resourcemetadata.xml and resourcemap.xml files. I tried to manually run ibun command and it succeeded. Then I manually ran irule command to run bagit rule, last time when I ran the irule command, I passed in the wrong parameters hence the SYS_INTERNAL_ERR. This time I looked into the code more carefully and manually ran the irule command with exactly the same input parameters, and irule command succeeded and created expected manifest files and bagit.txt file correctly. However, when I manually did a ibun command again with manifest files included this time, ibun raises this ```UNIX_FILE_LINK_ERR, directory not empty``` - the same exception message as we saw it the log for this resource. I looked at the added manifest files both logically using icommands, and also the physical files in iRODS vault, and they all look exactly like other files including permissions. I ran out of ideas and things to try further. Given the fact that this resource works on beta but not on www, and the iRODS on production has not been upgraded to the latest version, and iRODS latest version has upgraded libarchive version which ibun is based on, I suggest we wait until iRODS is upgraded on production, then test this resource again. If the same problem persists, we would need iRODS experts to help debug this since I ran out of things I could do at this point.

**Comment by hyi** [comment]
@rayi113 @dtarb I have just verified this has been fixed, most likely due to the iRODS upgrade. Could you please verify and close if it indeed works now?

**Comment by rayi113** [comment]
@hyi I tested this and it works, thanks!  Closing issue.

**Comment by dtarb** [comment]
@rayi113 did you check the file you downloaded.  I just downloaded the bag.  Then when I unzipped I got the following warning
![image](https://user-images.githubusercontent.com/3456833/63316774-5e701a00-c2cd-11e9-8a95-91807286aafa.png)

Then when I looked in the bag and attempted to unzip the contents file I got
![image](https://user-images.githubusercontent.com/3456833/63316816-8a8b9b00-c2cd-11e9-936b-97d3653469e5.png)

Thus I am still not able to access the contents of this resource.

**Comment by rayi113** [comment]
@dtarb Yes.  I tried everything from scratch just now to double-check.  I created this public resource just now that contains 2 PDFs: https://www.hydroshare.org/resource/52c6dfb776a24f19a9cbb04906b31199/

Then, before doing anything else so as to test creation of a zip file before it is copied to iRODS, I selected the "Copy Resource Bag to iRODS User Zone" button in the resource landing page file browsing area:
![199_pdf](https://user-images.githubusercontent.com/2846017/63317852-5cfd1c80-c2e2-11e9-9c10-889ab0a98f4e.png)

Then I login to users.hydroshare.org and do an "iget 52c6dfb776a24f19a9cbb04906b31199.zip"

Than I download 52c6dfb776a24f19a9cbb04906b31199.zip to my local windows PC (with ftp).

Then I double-click the 52c6dfb776a24f19a9cbb04906b31199.zip file in Windows and am able to browse the compressed .zip directory natively.

I can also do a right-click "Extract all..." on 52c6dfb776a24f19a9cbb04906b31199.zip in Windows and can also browse this resulting extracted directory natively.

**Comment by dtarb** [comment]
@rayi113 those are tests with small files.  We still have a problem with the resource @ChristinaB mentioned https://www.hydroshare.org/resource/ec518c49772b420b97047f7482ae92aa/ that started this issue.  I am unable to unzip the file downloaded from it, though I am now able to download a bag and download the file - which is progress from April 2018.  It may be that the zip file in this resource is corrupt.  I do not know if Christina has access to the original data to fix.

In any event there is still a problem.

**Comment by rayi113** [comment]
@dtarb I verified the original file in @ChristinaB 's https://www.hydroshare.org/resource/ec518c49772b420b97047f7482ae92aa/  resource is corrupt.  I did this by logging into data.hydroshare.org and copying the raw LNWB_DataAppendix_20121231.zip via linux cp into a local linux directory, then did a "7z l LNWB_DataAppendix_20121231.zip" and it says it cannot read it as a .zip file.

**Comment by rayi113** [comment]
@dtarb So that we may close this issue, I was able to find a zip program that could read a lot of the files in Christina's .zip file, but not all of them (i.e. thinking Christina's NWB_DataAppendix_20121231.zip is corrupt), so I unzipped what I could and then re-zipped just those files for testing purposes only since it is most of the files.  The thinking is the 2.8GB file I created should be sufficient for continued testing.  I put the resource here:  https://www.hydroshare.org/resource/ef94ad04be534a459980dcbe2b634bc7/ 

Could you try to download the bag for that and unzip it?  Thanks.

**Comment by dtarb** [comment]
I am able to download and unzip this file as well as the bag.  So we know that HydroShare is now handling this file size OK.  @ChristinaB Ray would like to close this issue.  I think that what is possible to do has been done.  Whatever system problems there may have been that caused this are fixed.  However the zip file in the resource you mention is still broken.  I suggest you either download the zip file in the new resource Ray created, check if its contents are what you want and upload it to the original resource to replace the broken one, or replace the broken one from its original source.
