### ISSUE TITLE
DEBUG = False causes login page to not render as expected

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#463]
Setting the DEBUG flag to False in local_settings.py causes the HydroShare login page to render oddly..
This can be set back to True and the login page renders normally again.

This is presently observable on dev.

This should be resolved so that we can run www.hydroshare.org in the DEBUG = False mode so users do not see our stack trace on error.

![screen shot 2015-06-03 at 5 43 25 pm](https://cloud.githubusercontent.com/assets/5332509/7972130/0af73c9a-0a18-11e5-9cdc-15d65bdcf756.png)

**Comment by pkdash** [comment]
@mjstealey It seems the settings ```ALLOWED_HOSTS = "*"``` needs to be changed as described here https://docs.djangoproject.com/en/1.7/releases/1.5/#allowed-hosts-required-in-production

This may solve this issue.

**Comment by pkdash** [comment]
@mjstealey This may be related to serving static files when DEBUG is set to FALSE. Not sure if this documentation here https://docs.djangoproject.com/en/dev/howto/static-files/deployment/ can help resolve this issue.

**Comment by ironfroggy** [comment]
This is best resolved by putting a proper Nginx and Apache server up and running Hydroshare via a WSGI gateway with static and media served up by the native webserver, as detailed in the Django deployment help.

**Comment by hyi** [comment]
@mjstealey is working on getting Nginx integrated into HS development and deployment workflow, so this should be fixed when that is done. Added Release 1.6 milestone.

**Comment by hyi** [comment]
@mjstealey now that Nginx is integrated into HS development and deployment workflow, is this issue resolved and ready to close?

**Comment by hyi** [comment]
@mjstealey could you check and close this issue if it is resolved with the current development and deployment setup?

**Comment by mjstealey** [comment]
Using nginx to serve static files has resolved this issue

**Comment by ironfroggy** [comment]
But, we don't all use nginx? It is an optional setting. If you're going to
support the setting to not run with nginx, doesn't this ticket still need
fixed?

I am still unable to use nginx and the SSL certifications when running from
boot2docker, because the certifications don't include the right addresses.

On Wed, Sep 2, 2015 at 10:07 AM, Michael J. Stealey <
notifications@github.com> wrote:

> Using nginx to serve static files has resolved this issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/463#issuecomment-137093685>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by hyi** [comment]
@ironfroggy @mjstealey With the current development/deployment settings, should we always set DEBUG=TRUE in our local dev environment and only set DEBUG=FALSE when setting nginx to TRUE to mimic deployment env? I am able to use nginx and the SSL self-certificate in my local dev env, so not sure whether boot2docker is the culprit that prevents SSL self-certs from working, but we can also set nginx to True with SSL set to False if self-certs has issues, right?
