### ISSUE TITLE
Release Candidate 1.5.3:  Time Series Method Metadata Edit not Working

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#587]
When I create a new time series resource from scratch with no ODM2 file and then try to enter metadata, the metadata update fails when I try to edit the Method information under the Time Series Specific metadata. When I click the "Save Changes" button I get a temporary red banner at the top that says "Error. Metadata failed to update."

Update:  I'm not sure this is just an issue with the release candidate.  It may have existed before, but I discovered it in testing and I'm guessing it will be an easy fix.

**Comment by horsburgh** [comment]
Update - I believe this is because the form is validating the MethodCode to limit it to an Integer as input.  It should be a string.

**Comment by pkdash** [comment]
@horsburgh Most likely this bug exists on www.hydroshare.org. It should be an easy fix but would require a new migration file as the data type of the model attribute needs to be changed from int to string.

**Comment by horsburgh** [comment]
This is the same as #340. I'm going to close that one and leave this one.

**Comment by horsburgh** [comment]
I just verified that this is still an issue on www.hydroshare.org.

**Comment by pkdash** [comment]
@horsburgh I am working to fix this issue now. How big the string we expect for the 'MethodCode'?

**Comment by horsburgh** [comment]
@pkdash - it's a code, so 50 characters is sufficient and consistent with the ODM2 design.

**Comment by pkdash** [comment]
@horsburgh Sounds good.

**Comment by pkdash** [comment]
@horsburgh I have deployed the fix to this issue at riverdev.hydroshare.org in case you want to test.

**Comment by horsburgh** [comment]
@pkdash - I just tried this on riverdev.hydroshare.org.  I went to my one time series resource:

https://riverdev.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/ 

I started editing and changed the MethodCode from "28" to "ODMTools" in the resource specific metadata.  It still throws an error when I try to save.

**Comment by pkdash** [comment]
@horsburgh The code for this branch is no more running on riverdev. You can test it on dev.hydroshare.org

**Comment by horsburgh** [comment]
@pkdash - I had to log in as admin to test because I never got an email notification to activate the account that I created, but this specific issue seems to be working OK now.

**Comment by pkdash** [comment]
@horsburgh See if this can be closed.

**Comment by horsburgh** [comment]
Verified working on www.hydroshare.org.
